// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcDcZA9BeBCV4kCqrESfCf3tRKPZiCirA',
    appId: '1:954200616397:web:6576b09ca8ff7fcc3c2884',
    messagingSenderId: '954200616397',
    projectId: 'crud-app-42c4f',
    authDomain: 'crud-app-42c4f.firebaseapp.com',
    storageBucket: 'crud-app-42c4f.appspot.com',
    measurementId: 'G-KGMSFT9NV8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC188_u3T2rLkHu259u3NwPXTLGB0vH7UY',
    appId: '1:954200616397:android:31b6db43d119f66b3c2884',
    messagingSenderId: '954200616397',
    projectId: 'crud-app-42c4f',
    storageBucket: 'crud-app-42c4f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwXBzto2f_QR5zEKjnSDjj3p5ocNyKF0I',
    appId: '1:954200616397:ios:c5653d0a413b0a013c2884',
    messagingSenderId: '954200616397',
    projectId: 'crud-app-42c4f',
    storageBucket: 'crud-app-42c4f.appspot.com',
    iosBundleId: 'com.example.crudApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwXBzto2f_QR5zEKjnSDjj3p5ocNyKF0I',
    appId: '1:954200616397:ios:c5653d0a413b0a013c2884',
    messagingSenderId: '954200616397',
    projectId: 'crud-app-42c4f',
    storageBucket: 'crud-app-42c4f.appspot.com',
    iosBundleId: 'com.example.crudApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcDcZA9BeBCV4kCqrESfCf3tRKPZiCirA',
    appId: '1:954200616397:web:2c801b81caf841033c2884',
    messagingSenderId: '954200616397',
    projectId: 'crud-app-42c4f',
    authDomain: 'crud-app-42c4f.firebaseapp.com',
    storageBucket: 'crud-app-42c4f.appspot.com',
    measurementId: 'G-ZJ22X9JVVB',
  );
}
